#!/bin/bash

#For Raspberry pi 1, and Raspberry Pi Zero W, use:
#wget https://dl.grafana.com/oss/release/grafana-rpi_6.2.2_armhf.deb 
#sudo dpkg -i grafana-rpi_6.2.2_armhf.deb

#For Raspberry pi 2, and Raspberry Pi 3, 3B, 3B+, use:

if [ ! -f ./grafana_6.2.2_armhf.deb ]; then
	wget https://dl.grafana.com/oss/release/grafana_6.2.2_armhf.deb 
fi
sudo dpkg -i grafana_6.2.2_armhf.deb

sudo systemctl start grafana-server
systemctl status grafana-server
