version: "3"

networks:
  metrics:
    external: false

services:
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    networks: [metrics]
    restart: always
    # user: "1000" # needs to be `id -u` // alternatively chown the grafana/data dir to 472:472
    ports:
      - "3000:3000" # expose for localhost
    volumes:
      - $TEMP_LOGGER_HOME/docker/grafana/data:/var/lib/grafana # data path
      - $TEMP_LOGGER_HOME/docker/grafana/grafana.ini:/etc/grafana/grafana.ini # - $TEMP_LOGGER_HOME/docker/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

  influxdb:
    image: influxdb:1.8.4
    container_name: influxdb
    restart: always
    networks: [metrics]
    ports:
      - "8086:8086"
    volumes:
      - ${TEMP_LOGGER_HOME}/docker/influxdb/data:/var/lib/influxdb
      - ${TEMP_LOGGER_HOME}/docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ${TEMP_LOGGER_HOME}/docker/influxdb/init:/docker-entrypoint-initdb.d
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME} # sourced from .env
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD} # sourced from .env

  telegraf:
    image: telegraf:latest
    restart: always
    container_name: telegraf
    networks: [metrics]
    volumes:
      - ${TEMP_LOGGER_HOME}/docker/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro

  chronograf:
    container_name: chronograf
    restart: always
    image: chronograf:latest
    ports:
      - "127.0.0.1:8888:8888"
    depends_on:
      - influxdb
    networks: [metrics]
    environment:
      - INFLUXDB_URL=http://influxdb:8086 # needs to match container_name
      - INFLUXDB_USERNAME=${INFLUXDB_USERNAME} # sourced from .env
      - INFLUXDB_PASSWORD=${INFLUXDB_PASSWORD} # sourced from .env
